server:
  port: 88
spring:
  application:
    name: provider

feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:83/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"